server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        health-check-path: /actuator/health
        health-check-timeout: 3s
        health-check-interval: 10s
        health-check-critical-timeout: 90m
        query-passing: true
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        prefer-ip-address: true
        service-name: ${spring.application.name}
        ip-address: ${spring.cloud.client.ip-address}
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - StripPrefix=1
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/customer/**

        - id: reporting-service
          uri: lb://reporting
          predicates:
            - Path=/reports/**
          filters:
            - RewritePath=/reports/(?<remaining>.*), /api/v1/${remaining}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: TRACE
    org.springframework.cloud.gateway.handler.predicate: TRACE
    org.springframework.cloud.gateway.handler.FilteringWebHandler: TRACE
    org.springframework.cloud.consul.discovery: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.gateway.filter.GatewayMetricsFilter: DEBUG
